image: python:3.6

variables:
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - python -m venv venv
  - source venv/bin/activate

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - apt-get update -qy
    - pip install -r requirements.txt
    - pip install codecov
  artifacts:
    paths:
      - .cache/pip
      - venv/

test:
  stage: test
  script: 
  - pytest --cov=./
  - codecov --token=CODECOV_TOKEN
